# Generated by Django 4.0.1 on 2022-02-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0003_customerg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerG',
        ),
    ]
